name: flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.6.0
  flutter: 2.5.3

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: 2.5.4
  flutter_hooks: 0.20.5
  chat_bubbles: 1.6.0
  cupertino_icons: 1.0.8

  firebase_core: ^2.13.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13
  freezed: 2.5.7
  flutter_lints: 5.0.0

flutter:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/profilePictures/

  uses-material-design: true